if(EXISTS "/Users/wldarden/learning/botany/build_debug/botany_tests-b12d07c_tests.cmake")
  include("/Users/wldarden/learning/botany/build_debug/botany_tests-b12d07c_tests.cmake")
else()
  add_test(botany_tests_NOT_BUILT-b12d07c botany_tests_NOT_BUILT-b12d07c)
endif()
